In [1]:
def filter_odd_numbers(arr):
    return [x for x in arr if x % 2 != 0]
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
odd_numbers = filter_odd_numbers(arr)
print(odd_numbers)  # Output: [1, 3, 5, 7, 9]


[1, 3, 5, 7, 9]


In [2]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
    
    def bark(self):
        print(f"{self.name} says Woof!")
my_dog = Dog("Max", "Golden Retriever")
my_dog.bark() # Output: "Max says Woof!"


Max says Woof!


In [3]:
import numpy as np

# Create a numpy array of 100 random integers between 0 and 100
arr = np.random.randint(0, 100, 100)

# Print the measures of central tendency
print("Measures of central tendency:")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")

# Print the measures of spread
print("\nMeasures of spread:")
print(f"Standard deviation: {np.std(arr)}")
print(f"Range: {np.ptp(arr)}")


Measures of central tendency:
Mean: 48.81
Median: 45.0

Measures of spread:
Standard deviation: 30.972147164831824
Range: 98


In [4]:
class MyClass:
    def __init__(self):
        self.array = []
    
    def get_array(self):
        length = int(input("Enter the length of the array: "))
        for i in range(length):
            elem = int(input(f"Enter element {i+1}: "))
            self.array.append(elem)
        self.array.sort()
        return self.array
my_obj = MyClass()
sorted_array = my_obj.get_array()
print(sorted_array)


Enter the length of the array: 5
Enter element 1: 2
Enter element 2: 4
Enter element 3: 3
Enter element 4: 1
Enter element 5: 5
[1, 2, 3, 4, 5]


In [5]:
import numpy as np

# Create a 2D array of size 4x4 using a list
my_list = [[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12],
           [13, 14, 15, 16]]

# Convert the list to a numpy array
my_array = np.array(my_list)

# Extract the diagonal elements from the array
diagonal = np.diag(my_array)
print("Diagonal elements:", diagonal)

# Find the trace of the matrix
trace = np.trace(my_array)
print("Trace:", trace)

# Find the max and min element of each row in the matrix
max_row = np.amax(my_array, axis=1)
min_row = np.amin(my_array, axis=1)
print("Max element of each row:", max_row)
print("Min element of each row:", min_row)


Diagonal elements: [ 1  6 11 16]
Trace: 34
Max element of each row: [ 4  8 12 16]
Min element of each row: [ 1  5  9 13]


In [8]:
import numpy as np

# Create a 2D numpy array with shape (4, 5) where each element is a random float between 0 and 1
my_array = np.random.uniform(low=0, high=1, size=(4, 5))

# Print the resulting numpy array
print(my_array)


[[0.46577655 0.84695714 0.7074802  0.2720224  0.21436621]
 [0.90391759 0.83462704 0.87630419 0.81244449 0.28049731]
 [0.19756557 0.70309261 0.77712097 0.12122324 0.14248043]
 [0.34702125 0.02126157 0.9096     0.48453868 0.06332528]]


In [10]:
import numpy as np

# Create a 2D numpy array with shape (4, 4) where each element is a random integer between 0 and 100
my_array_a = np.random.randint(low=0, high=100, size=(4, 4))

# Create a 2D numpy array with shape (4, 5) where each element is a random float between 0 and 1
my_array_b = np.random.uniform(low=0, high=1, size=(4, 4))

# Multiply the numpy arrays created in Part A and Part B element-wise
result_array = my_array_a * my_array_b

# Print the resulting numpy array
print(result_array)


[[ 1.63317037  5.11884618 24.99871987  5.75071389]
 [ 9.1986288  11.95385768 28.0328142  32.80612453]
 [43.29118394  8.17317588 12.80795151 60.19529647]
 [50.0545511  90.90879597 23.49252506  9.38916249]]


In [12]:
import pandas as pd
import numpy as np

# Read in the CSV file and create a pandas dataframe with the data
df = pd.read_csv('DataSet.csv')

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Set the 'Date' column as the index of the dataframe
df.set_index('Date', inplace=True)

# Use pandas resample to group the data by month and calculate the mean closing price for each month
monthly_avg_close = df.resample('M')['Close'].mean()

# Convert the resulting pandas series to a numpy array
monthly_avg_close_np = monthly_avg_close.to_numpy()

# Print the resulting numpy array
print(monthly_avg_close_np)


[39.63111111 39.17142857 40.386      38.04869565 33.76666667 30.94142857
 24.51952381 26.08380952 30.363      32.95421053 31.89869565 28.61578947
 28.214     ]
